name: Tests

on: push

jobs:
  build:
    name: Setup Python Poetry Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Setup Poetry
        run: pip install poetry

      - name: Install Dependencies
        working-directory: ./backend
        run: poetry install

      - name: Run pytest
        working-directory: ./backend
        run: poetry run pytest

      - name: Run black
        working-directory: ./backend
        run: poetry run black . --check

      - name: Run isort
        working-directory: ./backend
        run: poetry run isort . --check